<?php

echo "<!DOCTYPE html>";
echo "<html lang=\"en\">";

echo "<head>";
echo "    <!--- Basic Page Needs  -->";
echo "    <meta charset=\"utf-8\">";
echo "    <title>Valuescrip||Proffering realtime solution to cogs...</title>";
echo "    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">";
echo "    <!-- Mobile Specific Meta  -->";
echo "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, maximum-scale=1\">";
echo "    <!-- CSS -->";
echo "    <link rel=\"stylesheet\" href=\"assets/css/bootstrap.min.css\">";
echo "    <link rel=\"stylesheet\" href=\"assets/css/jquery-ui.css\">";
echo "    <link rel=\"stylesheet\" href=\"assets/css/font-awesome.min.css\">";
echo "    <link rel=\"stylesheet\" href=\"assets/css/owl.carousel.min.css\">";
echo "    <link rel=\"stylesheet\" href=\"assets/css/slicknav.min.css\">";
echo "    <link rel=\"stylesheet\" href=\"assets/css/magnificpopup.css\">";
echo "    <link rel=\"stylesheet\" href=\"assets/css/jquery.mb.YTPlayer.min.css\">";
echo "    <link rel=\"stylesheet\" href=\"assets/css/typography.css\">";
echo "    <link rel=\"stylesheet\" href=\"assets/css/style.css\">";
echo "    <link rel=\"stylesheet\" href=\"assets/css/responsive.css\">";
echo "    <!-- Favicon -->";
echo "    <link rel=\"shortcut icon\" type=\"image/png\" href=\"assets/img/icon/favicon.ico\">";

echo "</head>";

echo "<body>";
echo "    <!-- preloader area start -->";
echo "    <div id=\"preloader\">";
echo "        <div class=\"spinner\"></div>";
echo "    </div>";
echo "    <!-- Valuescrip preloader area end -->";
echo "    <!-- header area start -->";
echo "    <header id=\"header\">";
echo "        <div class=\"header-area\">";
echo "            <div class=\"container\">";
echo "                <div class=\"row\">";
echo "                    <div class=\"menu-area\">";
echo "                        <div class=\"col-md-3 col-sm-12 col-xs-12\">";
echo "                            <div class=\"logo\">";
echo "                                <a href=\"index.html\"><img src=\"assets/img/icon/Hello.png\" alt=\"valusescrip logo goes here\"></a>";
echo "                            </div>";
echo "                        </div>";
echo "                        <div class=\"col-md-9 hidden-xs hidden-sm\">";
echo "                            <div class=\"main-menu\">";
echo "                                <nav class=\"nav-menu\">";
echo "                                    <ul>";
echo "                                        <li class=\"active\"><a href=\"#home\">Home</a></li>";
echo "                                        <li><a href=\"#feature\">Business</a></li>";
echo "                                        <li><a href=\"#health\">Health</a></li>";
echo "                                        <li><a href=\"#education\">Education</a></li>";
echo "                                        <li><a href=\"#directory\">Directory</a></li>";

/*
echo "                                        <li><a href=\"#blog\">Customized Solutions</a></li>";
echo "                                        <li><a href=\"#contact\">Contact</a></li>";
*/
echo "                                    </ul>";
echo "                                </nav>";
echo "                            </div>";
echo "                        </div>";
echo "                        <div class=\"col-sm-12 col-xs-12 visible-sm visible-xs\">";
echo "                            <div class=\"mobile_menu\"></div>";
echo "                        </div>";
echo "                    </div>";
echo "                </div>";
echo "            </div>";
echo "        </div>";
echo "    </header>";
echo "    <!-- header area end -->";
echo "    <!-- slider area start -->";
echo "    <section id=\"home\" class=\"slider-area background-video\">";
echo "        <!-- bacground video start-->";
echo "        <div id=\"fullscreen-video\">";
echo "            <a id=\"bgndVideo\" class=\"player\" data-property=\"{videoURL:'https://youtu.be/4nbhfrQfRRE',containment:'.background-video', showControls:false, autoPlay:true, loop:false, vol:50, mute:false, startAt:0,ratio:16/9, stopAt:150, opacity:1, addRaster:false, quality:'hd720', optimizeDisplay:true}\"></a>";
echo "        </div>";
echo "        <!-- bacground video end-->";
echo "        <div class=\"container\">";
echo "            <div class=\"col-md-6 col-sm-6 hidden-xs\">";
echo "                <div class=\"row\">";
echo "                    <div class=\"slider-img\">";
echo "                        <img src=\"assets/img/about/Debby.jpg\">";
echo "                    </div>";
echo " 						<div id=\"slideshow\">";
echo "                        <div>";
echo "                       	<img src=\"assets/img/slider/App2.png\">";
echo "                        </div>";
echo "                        <div>";
echo "                       	<img src=\"assets/img/slider/App2.png\">";
echo "                        </div>";
echo "                      </div>";
echo "                </div>";
echo "            </div>";
echo "            <div class=\"col-md-6 col-sm-6 col-xs-12\">";
echo "                <div class=\"row\">";
echo "                    <div class=\"slider-inner text-right\">";
echo "                        <h2>1 App, 2 Platforms, </h2>";
echo "                        <h2>4 Modules,</h2>";
echo "                        <h5>#16 Nuggets#,</h5>";
echo "                        <h5>256 Suites..</h5>";
echo "                        <h5>it's just about digitizing your daily routines</h5>";
echo "                        <a class=\"expand-video\" href=\"https://www.youtube.com\"><i class=\"fa fa-play\"></i>Valued essence</a>";

echo "                    </div>";
echo "                </div>";
echo "            </div>";
echo "        </div>";
echo "    </section>";
echo "    <!-- slider area end -->";
echo "    <!-- service area start -->";
echo "    <div class=\"service-area\">";
echo "        <div class=\"container\">";
echo "            <div class=\"row\">";
echo "                <div class=\"col-md-4 col-sm-4 col-xs-12\">";
echo "                    <div class=\"service-single\">";
echo "                        <img src=\"assets/img/service/resourcemanagement.png\" alt=\"service image\">";
echo "                        <h2>Resource Management</h2>";
echo "                        <p>Ascertaining optimal value of resources</p>";
echo "                    </div>";
echo "                </div>";
echo "                <div class=\"col-md-4 col-sm-4 col-xs-12 col-6\">";
echo "                    <div class=\"service-single\">";
echo "                        <img src=\"assets/img/service/growthindex.jpg\" alt=\"service image\">";
echo "                        <h2>Growth Indexing</h2>";
echo "                        <p>Reliable Blueprint for logical inference with time</p>";
echo "                    </div>";
echo "                </div>";
echo "                <div class=\"col-md-4 col-sm-4 col-xs-12 col-6\">";
echo "                    <div class=\"service-single\">";
echo "                        <img src=\"assets/img/service/maximumproductivity.jpg\" alt=\"service image\">";
echo "                        <h2>Maximum Productivity</h2>";
echo "                        <p>Cog Osctracisation for maximum yield</p>";
echo "                    </div>";
echo "                </div>";
echo "            </div>";
echo "        </div>";
echo "    </div>";
echo "    <!-- service area end -->";
echo "    <!-- about area start -->";
echo "    <div class=\"about-area ptb--100\">";
echo "        <div class=\"container\">";
echo "            <div class=\"section-title\">";
echo "                <h2>Valuescrip</h2>";
echo "                <p> Valuescrip is hinged upon proffering real time solutions to cog through automation of daily routines as a core value in ascertaining logical inferential procession</p>";
echo "            </div>";
echo "            <div class=\"row d-flex flex-center\">";
echo "                <div class=\"col-md-6 col-sm-6 hidden-xs\">";
echo "                    <div class=\"about-left-img\">";
echo "                        <img src=\"assets/img/about/App2.png\" alt=\"frontpage\">";
echo "                    </div>";
echo "                </div>";

echo "                <div class=\"col-md-6 col-sm-6 col-xs-12 d-flex flex-center\">";
echo "                    <div class=\"about-content\">";
echo "                        <p>Valuescrip is saddled with processes that with direct connections to resource and business growths thereby availing tools for efficient logical inferencing, this cuts across different works of life ranging from Education to health, business and other walks of life.</p>";
echo "                        <p>Our suites are geared towards maximum productivity with based on designated needs</p>";
echo "                    </div>";
echo "                </div>";
echo "            </div>";
echo "        </div>";
echo "    </div>";
echo "    <!-- about area end -->";

/*

echo "    <!-- testimonial carousel area start -->";
echo "    <div class=\"testimonial-area ptb--100\">";
echo "        <div class=\"container\">";
echo "            <div class=\"section-title\">";
echo "                <h2>Our Core Values</h2>";
echo "                <p>Proffering real time solutions to cog through automation of daily routines as a core value in ascertaing absolute relief from psychological stress</p>";
echo "            </div>";
echo "            <div class=\"testimonial-slider owl-carousel\">";
echo "                <div class=\"single-tst\">";
echo "                    <h4>Online Directory</h4>";
echo "                    <span>Founder</span>";
echo "                    <p>proper preparation prevent poor performance proper preparation prevent poor performance proper preparation prevent poor performance</p>";
echo "                    <ul class=\"tst-social\">";
echo "                        <li><a href=\"#\"><i class=\"fa fa-facebook\"></i></a></li>";
echo "                        <li><a href=\"#\"><i class=\"fa fa-twitter\"></i></a></li>";
echo "                        <li><a href=\"#\"><i class=\"fa fa-linkedin\"></i></a></li>";
echo "                        <li><a href=\"#\"><i class=\"fa fa-dribbble\"></i></a></li>";
echo "                        <li><a href=\"#\"><i class=\"fa fa-ponterest\"></i></a></li>";
echo "                    </ul>";
echo "                </div>";
echo "                <div class=\"single-tst\">";
echo "                    <h4>Olamilekan Ahmad</h4>";
echo "                    <span>Sofware Engineer</span>";
echo "                    <p>proper preparation prevent poor performance proper preparation prevent poor performance proper preparation prevent poor performance proper preparation prevent poor performance</p>";
echo "                    <ul class=\"tst-social\">";
echo "                        <li><a href=\"#\"><i class=\"fa fa-facebook\"></i></a></li>";
echo "                        <li><a href=\"#\"><i class=\"fa fa-twitter\"></i></a></li>";
echo "                        <li><a href=\"#\"><i class=\"fa fa-linkedin\"></i></a></li>";
echo "                        <li><a href=\"#\"><i class=\"fa fa-dribbble\"></i></a></li>";
echo "                        <li><a href=\"#\"><i class=\"fa fa-ponterest\"></i></a></li>";
echo "                    </ul>";
echo "                </div>";
echo "                <div class=\"single-tst\">";
echo "                    <h4>Olamilekan Ahmad</h4>";
echo "                    <span>CEO</span>";
echo "                    <p>proper preparation prevent poor performance proper preparation prevent poor performance proper preparation prevent poor performance</p>";
echo "                    <ul class=\"tst-social\">";
echo "                        <li><a href=\"#\"><i class=\"fa fa-facebook\"></i></a></li>";
echo "                        <li><a href=\"#\"><i class=\"fa fa-twitter\"></i></a></li>";
echo "                        <li><a href=\"#\"><i class=\"fa fa-linkedin\"></i></a></li>";
echo "                        <li><a href=\"#\"><i class=\"fa fa-dribbble\"></i></a></li>";
echo "                        <li><a href=\"#\"><i class=\"fa fa-ponterest\"></i></a></li>";
echo "                    </ul>";
echo "                </div>";
echo "                <div class=\"single-tst\">";
echo "                    <h4>Ahmad Olamilekan</h4>";
echo "                    <span>CEO</span>";
echo "                    <p> proper preparation prevent poor performance proper preparation prevent poor performance proper preparation prevent poor performance</p>";
echo "                    <ul class=\"tst-social\">";
echo "                        <li><a href=\"#\"><i class=\"fa fa-facebook\"></i></a></li>";
echo "                        <li><a href=\"#\"><i class=\"fa fa-twitter\"></i></a></li>";
echo "                        <li><a href=\"#\"><i class=\"fa fa-linkedin\"></i></a></li>";
echo "                        <li><a href=\"#\"><i class=\"fa fa-dribbble\"></i></a></li>";
echo "                        <li><a href=\"#\"><i class=\"fa fa-ponterest\"></i></a></li>";
echo "                    </ul>";
echo "                </div>";
echo "            </div>";
echo "        </div>";
echo "    </div>";
echo "    <!-- testimonial carousel area end -->";


*/

echo "    <!-- feature area start -->";
echo "    <section class=\"feature-area bg-gray ptb--100\" id=\"feature\">";
echo "        <div class=\"container\">";
echo "            <div class=\"section-title\">";
echo "                <h2>Business</h2>";
echo "                <p>Manage your daily business routines for processional growth based on indexing with our business module for inventory, transactions, resource management and sales</p>";
echo "            </div>";
echo "            <div class=\"row\">";
echo "                <div class=\"col-md-4 col-sm-6 col-xs-12\">";
echo "                    <div class=\"ft-content rtl\">";
echo "                        <div class=\"ft-single\">";
echo "                            <img src=\"assets/img/icon/feature/1.png\" alt=\"icon\">";
echo "                            <div class=\"meta-content\">";
echo "                                <h2>Inventory Managements</h2>";
echo "                                <p>Stock dynamics infers business healths status at every point, make meaning of your commodity terrains per time while you sit back watch your business grow ensuring efficient resource delieveries</p>";
echo "                            </div>";
echo "                        </div>";
echo "                        <div class=\"ft-single\">";
echo "                            <img src=\"assets/img/icon/feature/2.png\" alt=\"icon\">";
echo "                            <div class=\"meta-content\">";
echo "                                <h2>Resource Management</h2>";
echo "                                <p>A fulfilled workforce replicate feats per time, avail your resource ease of delivery through digitization of daily routines with absolute relief from psychological stress</p>";
echo "                            </div>";
echo "                        </div>";
echo "                        <div class=\"ft-single\">";
echo "                            <img src=\"assets/img/icon/feature/3.png\" alt=\"icon\">";
echo "                            <div class=\"meta-content\">";
echo "                                <h2>Customer Relations</h2>";
echo "                                <p>Manage your patrons efficently being the essence of your business, happy customer, geometric proceeds</p>";
echo "                            </div>";
echo "                        </div>";
echo "                    </div>";
echo "                </div>";
echo "                <div class=\"col-md-4 hidden-sm col-xs-12\">";
echo "                    <div class=\"ft-screen-img\">";
echo "                        <img src=\"assets/img/mobile/ft-screen-img.png\" alt=\"image\">";
echo "                    </div>";
echo "                </div>";
echo "                <div class=\"col-md-4 col-sm-6 col-xs-12\">";
echo "                    <div class=\"ft-content\">";
echo "                        <div class=\"ft-single\">";
echo "                            <img src=\"assets/img/icon/feature/4.png\" alt=\"icon\">";
echo "                            <div class=\"meta-content\">";
echo "                                <h2>Sales Managements</h2>";
echo "                                <p>Ease the access to your acknowledgement overview with scrolls for efficient growth indexing</p>";
echo "                            </div>";
echo "                        </div>";
echo "                        <div class=\"ft-single\">";
echo "                            <img src=\"assets/img/icon/feature/5.png\" alt=\"icon\">";
echo "                            <div class=\"meta-content\">";
echo "                                <h2>Transaction Processional Managements</h2>";
echo "                                <p>Monitor cash flow with your finger tips with certainty of acclivitous edge per time.</p>";
echo "                            </div>";
echo "                        </div>";
echo "                        <div class=\"ft-single\">";
echo "                            <img src=\"assets/img/icon/feature/6.png\" alt=\"icon\">";
echo "                            <div class=\"meta-content\">";
echo "                                <h2>Efficient Connectivity</h2>";
echo "                                <p>Synchronize processes for maximum yield void of inordinate superfluities</p>";
echo "                            </div>";
echo "                        </div>";
echo "                    </div>";
echo "                </div>";
echo "            </div>";
echo "        </div>";
echo "    </section>";
echo "    <!-- feature area end -->";


echo "    <!-- blog area start -->";
echo "    <section class=\"blog-post ptb--100\" id=\"health\">";
echo "        <div class=\"container\">";
echo "            <div class=\"section-title\">";
echo "                <h2>Health</h2>";
echo "                <p>A free health diagonistic tool with a substantial confidence level for symptoms inference based on case entry with consultation channel to medical experts and other prescriptive measures</p>";
echo "            </div>";

/*
echo '<form action="welcome.php" method="post">';
echo 'Symptoms: <input type="text" name="symptoms"><br>';

echo '<input type="submit">';
echo '</form>';
*/
echo "        </div>";
echo "    </section>";
echo "    <!-- blog area end -->";
    
echo "    <!-- contact area start -->";


echo "    <section class=\"contact-area ptb--100\" id=\"education\">";
echo "        <div class=\"container\">";
echo "            <div class=\"section-title\">";
echo "                <h2>Education</h2>";
echo "                <p>Get the full commercial value for your intellectual prowess as an author at no cost with our content management studio that enables digital publication of your compendiums with the widest coverage of subscription you can ever imagine with respect to your anticipated audience</p>";
echo "            </div>";
echo "        </div>";
echo "    </section>";
echo "    <!-- contact area end -->";


echo "    <section class=\"contact-area ptb--100\" id=\"directory\">";
echo "        <div class=\"container\">";
echo "            <div class=\"section-title\">";
echo "                <h2>Directory</h2>";
echo "                <p>Navigate to the coordinate of your resource search with just a click to get connected</p>";
echo "            </div>";
echo "        </div>";
echo "    </section>";
echo "    <!-- contact area end -->";


echo "    <!-- video area start -->";

/*
echo "    <div class=\"video-area ptb--100\">";
echo "        <div class=\"container\">";
echo "            <div class=\"row\">";
echo "                <div class=\"col-md-8 col-md-offset-2 col-sm-10 col-sm-offset-1 col-xs-12\">";
echo "                    <h2>Watch Valuescrip Video Demo</h2>";
echo "                    <p>proper preparation prevent poor performance proper preparation prevent poor performance proper preparation prevent poor performance</p>";
echo "                    <a class=\"expand-video\" href=\"https://www.youtube.com/\"><i class=\"fa fa-play\"></i></a>";
echo "                </div>";
echo "            </div>";
echo "        </div>";
echo "    </div>";
*/
echo "    <!-- video area end -->";
echo "    <!-- pricing area start -->";
echo "    <section class=\"pricing-area ptb--100\" id=\"pricing\">";
echo "        <div class=\"container\">";
echo "            <div class=\"section-title\">";
echo "                <h2>Subscription Plans</h2>";
echo "                <p>Get the best plan that suites your need</p>";
echo "            </div>";
echo "            <div class=\"row\">";
echo "                <div class=\"col-md-4 col-sm-4 col-xs-12 col-6\">";
echo "                    <div class=\"single-price\">";
echo "                        <div class=\"prc-head\">";
echo "                            <span>Basic</span>";
echo "                            <h5><small>Free</small></h5>";
echo "                        </div>";
echo "                        <ul>";
echo "                            <li>1 User</li>";
echo "                            <li>Free Resource Account</li>";
echo "                            <li>Connect to patrons for free</li>";
echo "                            <li>Get Verified based on proficiency</li>";
echo "                            <li>Category: Authors,Teachers,Artisans...</li>";
echo "                        </ul>";
echo "                        <a href=\"#\">Learn More</a>";
echo "                    </div>";
echo "                </div>";
echo "                <div class=\"col-md-4 col-sm-4 col-xs-12 col-6\">";
echo "                    <div class=\"single-price\">";
echo "                        <div class=\"prc-head\">";
echo "                            <span>Enterprise</span>";
echo "                            <h5><small>Free</small></h5>";
echo "                        </div>";
echo "                        <ul>";
echo "                            <li>1-5 Linked Resource Accounts</li>";
echo "                            <li>Digitize your daily routines</li>";
echo "                            <li>Index your Business Growth processionally</li>";
echo "                            <li>Get verified to ascertain Quality assurance to patrons</li>";
echo "                            <li>Category:Stores,Infant SMEs,Closed-User-Groups</li>";
echo "                        </ul>";
echo "                        <a href=\"#\">Learn More</a>";
echo "                    </div>";
echo "                </div>";
echo "                <div class=\"col-md-4 col-sm-4 col-xs-12 col-6\">";
echo "                    <div class=\"single-price\">";
echo "                        <div class=\"prc-head\">";
echo "                            <span>Corporate</span>";
echo "                            <h5><small>Highly Affordable</small></h5>";
echo "                        </div>";
echo "                        <ul>";
echo "                            <li>Multiple Linked Resources</li>";
echo "                            <li>DIgitize your Processes</li>";
echo "                            <li>Get Blueprint Inferences with clicks</li>";
echo "                            <li>24/7 Support to ensure minimal downtime</li>";
echo "                            <li>Category:Production plants, Educational institutions and other corporate entities</li>";
echo "                        </ul>";
echo "                        <a href=\"#\">Learn More</a>";
echo "                    </div>";
echo "                </div>";
echo "            </div>";
echo "        </div>";
echo "    </section>";
echo "    <!-- pricing area end -->";
echo "    <!-- call-action area start -->";
echo "    <section class=\"call-to-action ptb--100\" id=\"download\">";
echo "        <div class=\"container\">";
echo "            <div class=\"section-title text-white\">";
echo "                <h2>Downloads</h2>";
echo "                <p>Download Now!!!</p>";
echo "            </div>";
echo "            <div class=\"download-btns btn-area text-center\">";
echo "                <a href=\"#\"><i class=\"fa fa-android\"></i>Mobile</a>";
echo "                <a href=\"#\"><i class=\"fa fa-windows\"></i>Desktop</a>";
echo "            </div>";
echo "        </div>";
echo "    </section>";
echo "    <!-- call-action area end -->";



echo "    <!-- footer area start -->";
echo "    <footer>";
echo "        <div class=\"footer-area\">";
echo "            <div class=\"container\">";
echo "                <p>";
echo "Copyright ©<script>document.write(new Date().getFullYear());</script> All rights reserved | Valuescrip <i class=\"fa fa-heart-o\" aria-hidden=\"true\"></i> by <a href=\"https://valusescrip.com\" target=\"_blank\">proficient resources</a>";
echo "</p>";
echo "            </div>";
echo "        </div>";
echo "    </footer>";
echo "    <!-- footer area end -->";

echo "    <!-- Scripts -->";
echo "    <script src=\"assets/js/jquery-3.2.0.min.js\"></script>";
echo "    <script src=\"assets/js/jquery-ui.js\"></script>";
echo "    <script src=\"assets/js/bootstrap.min.js\"></script>";
echo "    <script src=\"assets/js/jquery.slicknav.min.js\"></script>";
echo "    <script src=\"assets/js/owl.carousel.min.js\"></script>";
echo "    <script src=\"assets/js/magnific-popup.min.js\"></script>";
echo "    <script src=\"assets/js/counterup.js\"></script>";
echo "    <script src=\"assets/js/jquery.waypoints.min.js\"></script>";
echo "    <script src=\"assets/js/jquery.mb.YTPlayer.min.js\"></script>";
echo "    <script src=\"assets/js/theme.js\"></script>";
echo "    <script src=\"assets/js/slider.js\"></script>";
echo "</body>";

echo "</html>";

?>